// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: callbacks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const callbackHasRating = `-- name: CallbackHasRating :one
SELECT EXISTS(SELECT 1 FROM callbacks_rating WHERE callback_request_id = $1) AS has_rating
`

func (q *Queries) CallbackHasRating(ctx context.Context, callbackRequestID int64) (bool, error) {
	row := q.db.QueryRow(ctx, callbackHasRating, callbackRequestID)
	var has_rating bool
	err := row.Scan(&has_rating)
	return has_rating, err
}

const countCallbacks = `-- name: CountCallbacks :one
SELECT COUNT(*) FROM callbacks_callbackrequest
`

func (q *Queries) CountCallbacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCallbacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCallback = `-- name: CreateCallback :one
INSERT INTO callbacks_callbackrequest (phone_number, team_id, status, requested_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms
`

type CreateCallbackParams struct {
	PhoneNumber   string `json:"phone_number"`
	TeamID        int64  `json:"team_id"`
	Status        string `json:"status"`
	RequestedByID int64  `json:"requested_by_id"`
}

func (q *Queries) CreateCallback(ctx context.Context, arg CreateCallbackParams) (CallbacksCallbackrequest, error) {
	row := q.db.QueryRow(ctx, createCallback,
		arg.PhoneNumber,
		arg.TeamID,
		arg.Status,
		arg.RequestedByID,
	)
	var i CallbacksCallbackrequest
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Status,
		&i.CallID,
		&i.Uniqueid,
		&i.Channel,
		&i.CreatedAt,
		&i.CallStartedAt,
		&i.CallEndedAt,
		&i.CallDuration,
		&i.ErrorMessage,
		&i.Transferred,
		&i.AdditionalQuestions,
		&i.RequestedByID,
		&i.VoteUuid,
		&i.SmsSent,
		&i.SmsSentAt,
		&i.VotedViaSms,
	)
	return i, err
}

const findStaleCallbacks = `-- name: FindStaleCallbacks :many
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest
WHERE status IN ('dialing','connecting','answered','waiting_rating','waiting_additional','transferring')
  AND call_started_at IS NOT NULL
  AND call_started_at < $1
`

func (q *Queries) FindStaleCallbacks(ctx context.Context, callStartedAt pgtype.Timestamptz) ([]CallbacksCallbackrequest, error) {
	rows, err := q.db.Query(ctx, findStaleCallbacks, callStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallbacksCallbackrequest{}
	for rows.Next() {
		var i CallbacksCallbackrequest
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.TeamID,
			&i.Status,
			&i.CallID,
			&i.Uniqueid,
			&i.Channel,
			&i.CreatedAt,
			&i.CallStartedAt,
			&i.CallEndedAt,
			&i.CallDuration,
			&i.ErrorMessage,
			&i.Transferred,
			&i.AdditionalQuestions,
			&i.RequestedByID,
			&i.VoteUuid,
			&i.SmsSent,
			&i.SmsSentAt,
			&i.VotedViaSms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallback = `-- name: GetCallback :one
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest WHERE id = $1
`

func (q *Queries) GetCallback(ctx context.Context, id int64) (CallbacksCallbackrequest, error) {
	row := q.db.QueryRow(ctx, getCallback, id)
	var i CallbacksCallbackrequest
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Status,
		&i.CallID,
		&i.Uniqueid,
		&i.Channel,
		&i.CreatedAt,
		&i.CallStartedAt,
		&i.CallEndedAt,
		&i.CallDuration,
		&i.ErrorMessage,
		&i.Transferred,
		&i.AdditionalQuestions,
		&i.RequestedByID,
		&i.VoteUuid,
		&i.SmsSent,
		&i.SmsSentAt,
		&i.VotedViaSms,
	)
	return i, err
}

const getCallbackByCallID = `-- name: GetCallbackByCallID :one
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest WHERE call_id = $1
`

func (q *Queries) GetCallbackByCallID(ctx context.Context, callID pgtype.UUID) (CallbacksCallbackrequest, error) {
	row := q.db.QueryRow(ctx, getCallbackByCallID, callID)
	var i CallbacksCallbackrequest
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Status,
		&i.CallID,
		&i.Uniqueid,
		&i.Channel,
		&i.CreatedAt,
		&i.CallStartedAt,
		&i.CallEndedAt,
		&i.CallDuration,
		&i.ErrorMessage,
		&i.Transferred,
		&i.AdditionalQuestions,
		&i.RequestedByID,
		&i.VoteUuid,
		&i.SmsSent,
		&i.SmsSentAt,
		&i.VotedViaSms,
	)
	return i, err
}

const getCallbackByVoteUUID = `-- name: GetCallbackByVoteUUID :one
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest WHERE vote_uuid = $1
`

func (q *Queries) GetCallbackByVoteUUID(ctx context.Context, voteUuid pgtype.UUID) (CallbacksCallbackrequest, error) {
	row := q.db.QueryRow(ctx, getCallbackByVoteUUID, voteUuid)
	var i CallbacksCallbackrequest
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Status,
		&i.CallID,
		&i.Uniqueid,
		&i.Channel,
		&i.CreatedAt,
		&i.CallStartedAt,
		&i.CallEndedAt,
		&i.CallDuration,
		&i.ErrorMessage,
		&i.Transferred,
		&i.AdditionalQuestions,
		&i.RequestedByID,
		&i.VoteUuid,
		&i.SmsSent,
		&i.SmsSentAt,
		&i.VotedViaSms,
	)
	return i, err
}

const listCallbacks = `-- name: ListCallbacks :many
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCallbacksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCallbacks(ctx context.Context, arg ListCallbacksParams) ([]CallbacksCallbackrequest, error) {
	rows, err := q.db.Query(ctx, listCallbacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallbacksCallbackrequest{}
	for rows.Next() {
		var i CallbacksCallbackrequest
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.TeamID,
			&i.Status,
			&i.CallID,
			&i.Uniqueid,
			&i.Channel,
			&i.CreatedAt,
			&i.CallStartedAt,
			&i.CallEndedAt,
			&i.CallDuration,
			&i.ErrorMessage,
			&i.Transferred,
			&i.AdditionalQuestions,
			&i.RequestedByID,
			&i.VoteUuid,
			&i.SmsSent,
			&i.SmsSentAt,
			&i.VotedViaSms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallbacksByTeam = `-- name: ListCallbacksByTeam :many
SELECT id, phone_number, team_id, status, call_id, uniqueid, channel, created_at, call_started_at, call_ended_at, call_duration, error_message, transferred, additional_questions, requested_by_id, vote_uuid, sms_sent, sms_sent_at, voted_via_sms FROM callbacks_callbackrequest
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCallbacksByTeamParams struct {
	TeamID int64 `json:"team_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCallbacksByTeam(ctx context.Context, arg ListCallbacksByTeamParams) ([]CallbacksCallbackrequest, error) {
	rows, err := q.db.Query(ctx, listCallbacksByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallbacksCallbackrequest{}
	for rows.Next() {
		var i CallbacksCallbackrequest
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.TeamID,
			&i.Status,
			&i.CallID,
			&i.Uniqueid,
			&i.Channel,
			&i.CreatedAt,
			&i.CallStartedAt,
			&i.CallEndedAt,
			&i.CallDuration,
			&i.ErrorMessage,
			&i.Transferred,
			&i.AdditionalQuestions,
			&i.RequestedByID,
			&i.VoteUuid,
			&i.SmsSent,
			&i.SmsSentAt,
			&i.VotedViaSms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCallbackResult = `-- name: UpdateCallbackResult :exec
UPDATE callbacks_callbackrequest
SET status = $2,
    call_id = COALESCE($3, call_id),
    call_ended_at = $4,
    call_duration = $5,
    transferred = $6,
    error_message = $7
WHERE id = $1
`

type UpdateCallbackResultParams struct {
	ID           int64              `json:"id"`
	Status       string             `json:"status"`
	CallID       pgtype.UUID        `json:"call_id"`
	CallEndedAt  pgtype.Timestamptz `json:"call_ended_at"`
	CallDuration *int32             `json:"call_duration"`
	Transferred  bool               `json:"transferred"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) UpdateCallbackResult(ctx context.Context, arg UpdateCallbackResultParams) error {
	_, err := q.db.Exec(ctx, updateCallbackResult,
		arg.ID,
		arg.Status,
		arg.CallID,
		arg.CallEndedAt,
		arg.CallDuration,
		arg.Transferred,
		arg.ErrorMessage,
	)
	return err
}

const updateCallbackSMSSent = `-- name: UpdateCallbackSMSSent :exec
UPDATE callbacks_callbackrequest
SET sms_sent = TRUE, sms_sent_at = NOW(), status = $2
WHERE id = $1
`

type UpdateCallbackSMSSentParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCallbackSMSSent(ctx context.Context, arg UpdateCallbackSMSSentParams) error {
	_, err := q.db.Exec(ctx, updateCallbackSMSSent, arg.ID, arg.Status)
	return err
}

const updateCallbackStatus = `-- name: UpdateCallbackStatus :exec
UPDATE callbacks_callbackrequest
SET status = $2, call_started_at = COALESCE($3, call_started_at)
WHERE id = $1
`

type UpdateCallbackStatusParams struct {
	ID            int64              `json:"id"`
	Status        string             `json:"status"`
	CallStartedAt pgtype.Timestamptz `json:"call_started_at"`
}

func (q *Queries) UpdateCallbackStatus(ctx context.Context, arg UpdateCallbackStatusParams) error {
	_, err := q.db.Exec(ctx, updateCallbackStatus, arg.ID, arg.Status, arg.CallStartedAt)
	return err
}

const updateCallbackVotedViaSMS = `-- name: UpdateCallbackVotedViaSMS :exec
UPDATE callbacks_callbackrequest
SET voted_via_sms = TRUE, status = 'completed'
WHERE id = $1
`

func (q *Queries) UpdateCallbackVotedViaSMS(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateCallbackVotedViaSMS, id)
	return err
}
