// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CallbacksCallbackrequest struct {
	ID                  int64              `json:"id"`
	PhoneNumber         string             `json:"phone_number"`
	TeamID              int64              `json:"team_id"`
	Status              string             `json:"status"`
	CallID              pgtype.UUID        `json:"call_id"`
	Uniqueid            *string            `json:"uniqueid"`
	Channel             *string            `json:"channel"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CallStartedAt       pgtype.Timestamptz `json:"call_started_at"`
	CallEndedAt         pgtype.Timestamptz `json:"call_ended_at"`
	CallDuration        *int32             `json:"call_duration"`
	ErrorMessage        *string            `json:"error_message"`
	Transferred         bool               `json:"transferred"`
	AdditionalQuestions *bool              `json:"additional_questions"`
	RequestedByID       int64              `json:"requested_by_id"`
	VoteUuid            pgtype.UUID        `json:"vote_uuid"`
	SmsSent             bool               `json:"sms_sent"`
	SmsSentAt           pgtype.Timestamptz `json:"sms_sent_at"`
	VotedViaSms         bool               `json:"voted_via_sms"`
}

type CallbacksRating struct {
	ID                int64              `json:"id"`
	CallbackRequestID int64              `json:"callback_request_id"`
	Rating            int32              `json:"rating"`
	Comment           *string            `json:"comment"`
	Timestamp         pgtype.Timestamptz `json:"timestamp"`
	PhoneNumber       string             `json:"phone_number"`
	TeamID            int64              `json:"team_id"`
	Date              pgtype.Date        `json:"date"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type TeamsRegion struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description string             `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
}

type TeamsTeam struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	RegionID    int64              `json:"region_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
}

type User struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	Password    string             `json:"password"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	IsActive    bool               `json:"is_active"`
	IsStaff     bool               `json:"is_staff"`
	IsSuperuser bool               `json:"is_superuser"`
	Role        string             `json:"role"`
	DateJoined  pgtype.Timestamptz `json:"date_joined"`
	LastLogin   pgtype.Timestamptz `json:"last_login"`
}
