// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AvgRating(ctx context.Context) (float64, error)
	CallbackHasRating(ctx context.Context, callbackRequestID int64) (bool, error)
	CountCallbacks(ctx context.Context) (int64, error)
	CountRatings(ctx context.Context) (int64, error)
	CreateCallback(ctx context.Context, arg CreateCallbackParams) (CallbacksCallbackrequest, error)
	CreateRating(ctx context.Context, arg CreateRatingParams) (CallbacksRating, error)
	CreateRegion(ctx context.Context, arg CreateRegionParams) (TeamsRegion, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (TeamsTeam, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRegion(ctx context.Context, id int64) error
	DeleteTeam(ctx context.Context, id int64) error
	FindStaleCallbacks(ctx context.Context, callStartedAt pgtype.Timestamptz) ([]CallbacksCallbackrequest, error)
	GetCallback(ctx context.Context, id int64) (CallbacksCallbackrequest, error)
	GetCallbackByCallID(ctx context.Context, callID pgtype.UUID) (CallbacksCallbackrequest, error)
	GetCallbackByVoteUUID(ctx context.Context, voteUuid pgtype.UUID) (CallbacksCallbackrequest, error)
	GetRatingByCallback(ctx context.Context, callbackRequestID int64) (CallbacksRating, error)
	GetRegion(ctx context.Context, id int64) (TeamsRegion, error)
	GetTeam(ctx context.Context, id int64) (TeamsTeam, error)
	GetTeamWithRegion(ctx context.Context, id int64) (GetTeamWithRegionRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActiveRegions(ctx context.Context) ([]TeamsRegion, error)
	ListActiveTeams(ctx context.Context) ([]ListActiveTeamsRow, error)
	ListCallbacks(ctx context.Context, arg ListCallbacksParams) ([]CallbacksCallbackrequest, error)
	ListCallbacksByTeam(ctx context.Context, arg ListCallbacksByTeamParams) ([]CallbacksCallbackrequest, error)
	ListRatings(ctx context.Context, arg ListRatingsParams) ([]CallbacksRating, error)
	ListRegions(ctx context.Context) ([]TeamsRegion, error)
	ListTeams(ctx context.Context) ([]ListTeamsRow, error)
	ListTeamsByRegion(ctx context.Context, regionID int64) ([]ListTeamsByRegionRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	RandomActiveTeam(ctx context.Context) (TeamsTeam, error)
	RatingDistribution(ctx context.Context) ([]RatingDistributionRow, error)
	RatingsByTeam(ctx context.Context, teamID int64) ([]CallbacksRating, error)
	RegionTeamCount(ctx context.Context, regionID int64) (int64, error)
	RegionTotalTeamCount(ctx context.Context, regionID int64) (int64, error)
	UpdateCallbackResult(ctx context.Context, arg UpdateCallbackResultParams) error
	UpdateCallbackSMSSent(ctx context.Context, arg UpdateCallbackSMSSentParams) error
	UpdateCallbackStatus(ctx context.Context, arg UpdateCallbackStatusParams) error
	UpdateCallbackVotedViaSMS(ctx context.Context, id int64) error
	UpdateRegion(ctx context.Context, arg UpdateRegionParams) (TeamsRegion, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (TeamsTeam, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
