// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlc

import (
	"context"
)

const avgRating = `-- name: AvgRating :one
SELECT COALESCE(AVG(rating), 0)::FLOAT8 AS avg_rating FROM callbacks_rating
`

func (q *Queries) AvgRating(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, avgRating)
	var avg_rating float64
	err := row.Scan(&avg_rating)
	return avg_rating, err
}

const countRatings = `-- name: CountRatings :one
SELECT COUNT(*) FROM callbacks_rating
`

func (q *Queries) CountRatings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRatings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRating = `-- name: CreateRating :one
INSERT INTO callbacks_rating (callback_request_id, rating, comment, phone_number, team_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, callback_request_id, rating, comment, timestamp, phone_number, team_id, date
`

type CreateRatingParams struct {
	CallbackRequestID int64   `json:"callback_request_id"`
	Rating            int32   `json:"rating"`
	Comment           *string `json:"comment"`
	PhoneNumber       string  `json:"phone_number"`
	TeamID            int64   `json:"team_id"`
}

func (q *Queries) CreateRating(ctx context.Context, arg CreateRatingParams) (CallbacksRating, error) {
	row := q.db.QueryRow(ctx, createRating,
		arg.CallbackRequestID,
		arg.Rating,
		arg.Comment,
		arg.PhoneNumber,
		arg.TeamID,
	)
	var i CallbacksRating
	err := row.Scan(
		&i.ID,
		&i.CallbackRequestID,
		&i.Rating,
		&i.Comment,
		&i.Timestamp,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Date,
	)
	return i, err
}

const getRatingByCallback = `-- name: GetRatingByCallback :one
SELECT id, callback_request_id, rating, comment, timestamp, phone_number, team_id, date FROM callbacks_rating WHERE callback_request_id = $1
`

func (q *Queries) GetRatingByCallback(ctx context.Context, callbackRequestID int64) (CallbacksRating, error) {
	row := q.db.QueryRow(ctx, getRatingByCallback, callbackRequestID)
	var i CallbacksRating
	err := row.Scan(
		&i.ID,
		&i.CallbackRequestID,
		&i.Rating,
		&i.Comment,
		&i.Timestamp,
		&i.PhoneNumber,
		&i.TeamID,
		&i.Date,
	)
	return i, err
}

const listRatings = `-- name: ListRatings :many
SELECT id, callback_request_id, rating, comment, timestamp, phone_number, team_id, date FROM callbacks_rating
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListRatingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRatings(ctx context.Context, arg ListRatingsParams) ([]CallbacksRating, error) {
	rows, err := q.db.Query(ctx, listRatings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallbacksRating{}
	for rows.Next() {
		var i CallbacksRating
		if err := rows.Scan(
			&i.ID,
			&i.CallbackRequestID,
			&i.Rating,
			&i.Comment,
			&i.Timestamp,
			&i.PhoneNumber,
			&i.TeamID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingDistribution = `-- name: RatingDistribution :many
SELECT rating, COUNT(*) AS count
FROM callbacks_rating
GROUP BY rating
ORDER BY rating
`

type RatingDistributionRow struct {
	Rating int32 `json:"rating"`
	Count  int64 `json:"count"`
}

func (q *Queries) RatingDistribution(ctx context.Context) ([]RatingDistributionRow, error) {
	rows, err := q.db.Query(ctx, ratingDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RatingDistributionRow{}
	for rows.Next() {
		var i RatingDistributionRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingsByTeam = `-- name: RatingsByTeam :many
SELECT id, callback_request_id, rating, comment, timestamp, phone_number, team_id, date FROM callbacks_rating WHERE team_id = $1 ORDER BY timestamp DESC
`

func (q *Queries) RatingsByTeam(ctx context.Context, teamID int64) ([]CallbacksRating, error) {
	rows, err := q.db.Query(ctx, ratingsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CallbacksRating{}
	for rows.Next() {
		var i CallbacksRating
		if err := rows.Scan(
			&i.ID,
			&i.CallbackRequestID,
			&i.Rating,
			&i.Comment,
			&i.Timestamp,
			&i.PhoneNumber,
			&i.TeamID,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
