// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions.sql

package sqlc

import (
	"context"
)

const createRegion = `-- name: CreateRegion :one
INSERT INTO teams_region (name, code, description, is_active, created_by_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, code, description, is_active, created_at, created_by_id
`

type CreateRegionParams struct {
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
	CreatedByID int64  `json:"created_by_id"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (TeamsRegion, error) {
	row := q.db.QueryRow(ctx, createRegion,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
		arg.CreatedByID,
	)
	var i TeamsRegion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM teams_region WHERE id = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRegion, id)
	return err
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, code, description, is_active, created_at, created_by_id FROM teams_region WHERE id = $1
`

func (q *Queries) GetRegion(ctx context.Context, id int64) (TeamsRegion, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i TeamsRegion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}

const listActiveRegions = `-- name: ListActiveRegions :many
SELECT id, name, code, description, is_active, created_at, created_by_id FROM teams_region WHERE is_active = TRUE ORDER BY name
`

func (q *Queries) ListActiveRegions(ctx context.Context) ([]TeamsRegion, error) {
	rows, err := q.db.Query(ctx, listActiveRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamsRegion{}
	for rows.Next() {
		var i TeamsRegion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, code, description, is_active, created_at, created_by_id FROM teams_region ORDER BY name
`

func (q *Queries) ListRegions(ctx context.Context) ([]TeamsRegion, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamsRegion{}
	for rows.Next() {
		var i TeamsRegion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionTeamCount = `-- name: RegionTeamCount :one
SELECT COUNT(*) FROM teams_team WHERE region_id = $1 AND is_active = TRUE
`

func (q *Queries) RegionTeamCount(ctx context.Context, regionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, regionTeamCount, regionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const regionTotalTeamCount = `-- name: RegionTotalTeamCount :one
SELECT COUNT(*) FROM teams_team WHERE region_id = $1
`

func (q *Queries) RegionTotalTeamCount(ctx context.Context, regionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, regionTotalTeamCount, regionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateRegion = `-- name: UpdateRegion :one
UPDATE teams_region
SET name = $2, code = $3, description = $4, is_active = $5
WHERE id = $1
RETURNING id, name, code, description, is_active, created_at, created_by_id
`

type UpdateRegionParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateRegion(ctx context.Context, arg UpdateRegionParams) (TeamsRegion, error) {
	row := q.db.QueryRow(ctx, updateRegion,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
	)
	var i TeamsRegion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}
