// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams_team (name, description, region_id, is_active, created_by_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, region_id, is_active, created_at, created_by_id
`

type CreateTeamParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	RegionID    int64  `json:"region_id"`
	IsActive    bool   `json:"is_active"`
	CreatedByID int64  `json:"created_by_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (TeamsTeam, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Description,
		arg.RegionID,
		arg.IsActive,
		arg.CreatedByID,
	)
	var i TeamsTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RegionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams_team WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, description, region_id, is_active, created_at, created_by_id FROM teams_team WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id int64) (TeamsTeam, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i TeamsTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RegionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}

const getTeamWithRegion = `-- name: GetTeamWithRegion :one
SELECT t.id, t.name, t.description, t.region_id, t.is_active, t.created_at, t.created_by_id, r.name AS region_name, r.code AS region_code
FROM teams_team t
JOIN teams_region r ON r.id = t.region_id
WHERE t.id = $1
`

type GetTeamWithRegionRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	RegionID    int64              `json:"region_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
	RegionName  string             `json:"region_name"`
	RegionCode  string             `json:"region_code"`
}

func (q *Queries) GetTeamWithRegion(ctx context.Context, id int64) (GetTeamWithRegionRow, error) {
	row := q.db.QueryRow(ctx, getTeamWithRegion, id)
	var i GetTeamWithRegionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RegionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
		&i.RegionName,
		&i.RegionCode,
	)
	return i, err
}

const listActiveTeams = `-- name: ListActiveTeams :many
SELECT t.id, t.name, t.description, t.region_id, t.is_active, t.created_at, t.created_by_id, r.name AS region_name, r.code AS region_code
FROM teams_team t
JOIN teams_region r ON r.id = t.region_id
WHERE t.is_active = TRUE
ORDER BY r.name, t.name
`

type ListActiveTeamsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	RegionID    int64              `json:"region_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
	RegionName  string             `json:"region_name"`
	RegionCode  string             `json:"region_code"`
}

func (q *Queries) ListActiveTeams(ctx context.Context) ([]ListActiveTeamsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTeamsRow{}
	for rows.Next() {
		var i ListActiveTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RegionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.RegionName,
			&i.RegionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, t.description, t.region_id, t.is_active, t.created_at, t.created_by_id, r.name AS region_name, r.code AS region_code
FROM teams_team t
JOIN teams_region r ON r.id = t.region_id
ORDER BY r.name, t.name
`

type ListTeamsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	RegionID    int64              `json:"region_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
	RegionName  string             `json:"region_name"`
	RegionCode  string             `json:"region_code"`
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RegionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.RegionName,
			&i.RegionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByRegion = `-- name: ListTeamsByRegion :many
SELECT t.id, t.name, t.description, t.region_id, t.is_active, t.created_at, t.created_by_id, r.name AS region_name
FROM teams_team t
JOIN teams_region r ON r.id = t.region_id
WHERE t.region_id = $1 AND t.is_active = TRUE
ORDER BY t.name
`

type ListTeamsByRegionRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	RegionID    int64              `json:"region_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedByID int64              `json:"created_by_id"`
	RegionName  string             `json:"region_name"`
}

func (q *Queries) ListTeamsByRegion(ctx context.Context, regionID int64) ([]ListTeamsByRegionRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsByRegionRow{}
	for rows.Next() {
		var i ListTeamsByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RegionID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedByID,
			&i.RegionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomActiveTeam = `-- name: RandomActiveTeam :one
SELECT id, name, description, region_id, is_active, created_at, created_by_id FROM teams_team WHERE is_active = TRUE ORDER BY random() LIMIT 1
`

func (q *Queries) RandomActiveTeam(ctx context.Context) (TeamsTeam, error) {
	row := q.db.QueryRow(ctx, randomActiveTeam)
	var i TeamsTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RegionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams_team
SET name = $2, description = $3, region_id = $4, is_active = $5
WHERE id = $1
RETURNING id, name, description, region_id, is_active, created_at, created_by_id
`

type UpdateTeamParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	RegionID    int64  `json:"region_id"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (TeamsTeam, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RegionID,
		arg.IsActive,
	)
	var i TeamsTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RegionID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return i, err
}
